# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [3]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[61, 30, 59, ..., 86, 81, 27],
       [25, 83, 67, ..., 66,  8, 85],
       [58, 30, 38, ..., 52, 90, 42],
       ...,
       [30, 20, 13, ..., 35, 17, 46],
       [30, 24, 69, ..., 92,  9, 73],
       [17, 41, 85, ..., 26, 24, 86]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [4]:
rng = np.random.default_rng()

rng.shuffle(A, axis=1)
A

array([[ 4, 61, 36, ..., 93, 90, 81],
       [38, 25, 27, ..., 95, 66,  8],
       [99, 58,  8, ..., 28, 13, 90],
       ...,
       [91, 30, 30, ...,  2,  2, 17],
       [16, 30, 71, ..., 14, 85,  9],
       [ 7, 17, 26, ..., 53,  1, 24]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [5]:
A[A[:, ::2].sum(axis=1) > A[:, 1::2].sum(axis=1).mean()]

array([[ 4, 61, 36, ..., 93, 90, 81],
       [38, 25, 27, ..., 95, 66,  8],
       [99, 88, 93, ..., 10, 77, 91],
       ...,
       [30, 11, 69, ..., 54, 42, 55],
       [51,  5, 20, ..., 32, 80, 22],
       [16, 30, 71, ..., 14, 85,  9]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [6]:
np.argmax(A.max(axis=1) - A.min(axis=1))

12

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [7]:
A.argsort(axis=None).argsort().reshape(A.shape) + 1

array([[ 433, 6155, 3669, ..., 9385, 9018, 8080],
       [3831, 2502, 2774, ..., 9528, 6664,  860],
       [9961, 5819,  862, ..., 2833, 1362, 9075],
       ...,
       [9115, 3051, 3052, ...,  249,  250, 1710],
       [1686, 3040, 7141, ..., 1426, 8550,  974],
       [ 766, 1781, 2642, ..., 5299,   96, 2468]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [8]:
(A - np.vstack(A.min(axis=1))) / np.vstack(A.max(axis=1) - A.min(axis=1))

array([[0.03061224, 0.6122449 , 0.35714286, ..., 0.93877551, 0.90816327,
        0.81632653],
       [0.38709677, 0.24731183, 0.2688172 , ..., 1.        , 0.68817204,
        0.06451613],
       [1.        , 0.58163265, 0.07142857, ..., 0.2755102 , 0.12244898,
        0.90816327],
       ...,
       [0.92857143, 0.30612245, 0.30612245, ..., 0.02040816, 0.02040816,
        0.17346939],
       [0.16666667, 0.3125    , 0.73958333, ..., 0.14583333, 0.88541667,
        0.09375   ],
       [0.06122449, 0.16326531, 0.25510204, ..., 0.53061224, 0.        ,
        0.23469388]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [73]:
A * np.arange(1, 11).reshape(10, 1, 1)

array([[[  4,  61,  36, ...,  93,  90,  81],
        [ 38,  25,  27, ...,  95,  66,   8],
        [ 99,  58,   8, ...,  28,  13,  90],
        ...,
        [ 91,  30,  30, ...,   2,   2,  17],
        [ 16,  30,  71, ...,  14,  85,   9],
        [  7,  17,  26, ...,  53,   1,  24]],

       [[  8, 122,  72, ..., 186, 180, 162],
        [ 76,  50,  54, ..., 190, 132,  16],
        [198, 116,  16, ...,  56,  26, 180],
        ...,
        [182,  60,  60, ...,   4,   4,  34],
        [ 32,  60, 142, ...,  28, 170,  18],
        [ 14,  34,  52, ..., 106,   2,  48]],

       [[ 12, 183, 108, ..., 279, 270, 243],
        [114,  75,  81, ..., 285, 198,  24],
        [297, 174,  24, ...,  84,  39, 270],
        ...,
        [273,  90,  90, ...,   6,   6,  51],
        [ 48,  90, 213, ...,  42, 255,  27],
        [ 21,  51,  78, ..., 159,   3,  72]],

       ...,

       [[ 32, 488, 288, ..., 744, 720, 648],
        [304, 200, 216, ..., 760, 528,  64],
        [792, 464,  64, ..., 224, 104, 720

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который состоит из средних этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте новый массив той же размерности, состоящий из суммы скользящих средних по окну $3$, $5$, $10$.

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [171]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 3, 0, 2, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [172]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

1800

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [173]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.